name: terraform-apply
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            
      - name: Terraform Init
        run: terraform init -reconfigure -backend-config="./terraform/dev/backend-gitops.tfbackend"

      - name: Terraform Plan
        run: terraform plan -var-file="./terraform/dev/terraform.tfvars"

      - name: Terraform Apply
        run: terraform apply -var-file="./terraform/dev/terraform.tfvars" -auto-approve

